import type { CategoryMeta, CityAlertIncident, Coordinates } from "./types";

export const GOMA_CENTER: Coordinates = [-1.6585, 29.2205];

export const categoryMeta: Record<CityAlertIncident["category"], CategoryMeta> = {
  danger: {
    label: "Danger / risque",
    shortLabel: "Danger",
    markerClass: "city-marker-danger",
    textClass: "text-red-200",
    badgeClass: "border-red-400/35 bg-red-500/15 text-red-100",
  },
  power: {
    label: "Coupure electrique",
    shortLabel: "Electricite",
    markerClass: "city-marker-power",
    textClass: "text-yellow-100",
    badgeClass: "border-yellow-300/35 bg-yellow-400/15 text-yellow-100",
  },
  traffic: {
    label: "Trafic / blocage",
    shortLabel: "Trafic",
    markerClass: "city-marker-traffic",
    textClass: "text-orange-100",
    badgeClass: "border-orange-300/35 bg-orange-400/15 text-orange-100",
  },
  service: {
    label: "Service utile",
    shortLabel: "Service",
    markerClass: "city-marker-service",
    textClass: "text-blue-100",
    badgeClass: "border-blue-300/35 bg-blue-500/15 text-blue-100",
  },
};

export const cityIncidents: CityAlertIncident[] = [
  {
    id: "route-sake-traffic",
    title: "Route de Sake bloquee",
    category: "danger",
    severity: "critical",
    location: "Route de Sake, pres de Ndosho",
    neighborhood: "Ndosho",
    description:
      "Signalement citoyen d'un blocage important avec circulation ralentie vers l'ouest.",
    timeAgo: "A l'instant",
    reportedAt: "20:24",
    status: "active",
    coordinates: [-1.6762, 29.1877],
    confidence: 91,
    source: "3 confirmations citoyennes",
    tags: ["Critique", "Trafic"],
  },
  {
    id: "katindo-power",
    title: "Maintenance reseau en cours",
    category: "power",
    severity: "planned",
    location: "Avenue du Lac, Katindo",
    neighborhood: "Katindo",
    description:
      "Coupure localisee signalee pendant une intervention technique sur le reseau.",
    timeAgo: "18 min",
    reportedAt: "20:06",
    status: "monitoring",
    coordinates: [-1.655, 29.2364],
    confidence: 78,
    source: "2 confirmations citoyennes",
    tags: ["Planifie", "Infrastructure"],
  },
  {
    id: "birere-traffic",
    title: "Trafic dense au marche",
    category: "traffic",
    severity: "attention",
    location: "Marche de Birere",
    neighborhood: "Birere",
    description:
      "Affluence elevee et stationnement difficile autour des axes commerciaux.",
    timeAgo: "31 min",
    reportedAt: "19:53",
    status: "active",
    coordinates: [-1.6844, 29.2294],
    confidence: 84,
    source: "Patrouille communautaire",
    tags: ["Attention", "Mobilite"],
  },
  {
    id: "himbi-service",
    title: "Pharmacie ouverte confirmee",
    category: "service",
    severity: "info",
    location: "Boulevard Kanyamuhanga, Himbi",
    neighborhood: "Himbi",
    description:
      "Service utile confirme par la communaute pour les besoins nocturnes urgents.",
    timeAgo: "46 min",
    reportedAt: "19:38",
    status: "active",
    coordinates: [-1.6687, 29.2253],
    confidence: 88,
    source: "Signalement verifie",
    tags: ["Info", "Sante"],
  },
  {
    id: "centre-danger",
    title: "Zone a risque signalee",
    category: "danger",
    severity: "attention",
    location: "Centre-ville, avenue du Commerce",
    neighborhood: "Centre-ville",
    description:
      "Regroupement inhabituel et passage recommande avec prudence dans le secteur.",
    timeAgo: "1 h",
    reportedAt: "19:24",
    status: "monitoring",
    coordinates: [-1.6614, 29.2218],
    confidence: 73,
    source: "Signalement citoyen",
    tags: ["Vigilance", "Securite"],
  },
  {
    id: "ndosho-power",
    title: "Quartier partiellement sans courant",
    category: "power",
    severity: "attention",
    location: "Ndosho, axe principal",
    neighborhood: "Ndosho",
    description:
      "Plusieurs foyers indiquent une interruption non planifiee depuis la soiree.",
    timeAgo: "1 h 22",
    reportedAt: "19:02",
    status: "active",
    coordinates: [-1.6705, 29.1988],
    confidence: 82,
    source: "5 confirmations citoyennes",
    tags: ["Attention", "Electricite"],
  },
];
